# Generated by Django 4.2.15 on 2025-10-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm', '0002_productcategory_myfarmproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfarmproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='myfarmproduct',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
