# Generated by Django 4.2.15 on 2025-10-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm', '0003_myfarmproduct_price_alter_myfarmproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='farmimages'),
        ),
    ]
